apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: od-dataset
spec:
  inputs:
    resources:
    - name: image
      type: image
  outputs:
    resources:
    - name: image
      type: image
  steps:
    - name: download
      image: $(inputs.resources.image.url)
      workingDir: /mlperf/object_detection
      resources:
        limits:
          memory: "16Gi"
          nvidia/gpu: "4"
        requests:
          memory: "12Gi"
          nvidia/gpu: "4"
      volumeMounts:
        - name: od-dataset-volume
          mountPath: /mlperf/object_detection/pytorch/datasets/coco
      securityContext:
        privileged: true
      command: ["/bin/sh", "./download_dataset.sh"]
