apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: od-dataset-run
  namespace: mlperf
spec:
  taskRef:
    name: od-dataset
  serviceAccount: mlperf
  inputs:
    resources:
      - name: image
        resourceRef:
          name: od-build-image
  outputs:
    resources:
      - name: image
        resourceRef:
          name: od-build-image
  timeout: "0"
  podTemplate:
    volumes:
    - name: od-dataset-volume
      persistentVolumeClaim:
        claimName: od-pvc
    - name: od-runtime-volume
      persistentVolumeClaim:
        claimName: od-runtime-pvc