apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: od-run
spec:
  inputs:
    params:
    - name: num_gpus
      type: string
    resources:
    - name: image
      type: image
  steps:
    - name: run
      image: $(inputs.resources.image.url)
      workingDir: /mlperf/object_detection
      volumeMounts:
        - name: od-dataset-volume
          mountPath: /mlperf/object_detection/pytorch/datasets/coco
        - name: od-runtime-volume
          mountPath: /dev/shm
      securityContext:
        privileged: true
      env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: 'all'
      - name: NGPUS
        value: '$NVIDIA_VISIBLE_DEVICES'
      command: ["/bin/sh"]
      args:
        - '-c'
        - |
          ./run_and_time.sh $(inputs.params.num_gpus)
  