apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: od-taskrun
  namespace: mlperf
spec:
  taskRef:
    name: od-run
  serviceAccount: mlperf
  inputs:
    resources:
      - name: od-build-image
        resourceRef:
          name: od-build-image