---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: rnn-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/raynalee4/mlperf-training.git
    - name: revision
      value: rnn-translator
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: rnn-build-image
spec:
  type: image
  params:
    - name: url
      value: docker-registry.default.svc:5000/mlperf/rnn-translator:latest
---