apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: image-classification-pipeline-run-
spec:
  serviceAccount: mlperf
  pipelineRef:
    name: image-classification
  resources:
  - name: repo
    resourceRef:
      name: ic-repo
  - name: build-image
    resourceRef:
      name: ic-build-image
