apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: image-classification-pipeline-run-
spec:
  serviceAccount: mlperf
  pipelineRef:
    name: mlperf-pipeline
  params:
    - name: DOCKERFILE
      value: image_classification/tensorflow/Dockerfile
    - name: DATASET_DIR
      value: "image_classification"
    - name: RUN_DIR
      value: "image_classification/tensorflow"
  resources:
  - name: repo
    resourceRef:
      name: ic-repo
  - name: build-image
    resourceRef:
      name: ic-build-image