---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: ic-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/AICoE/mlperf-training.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: ic-build-image
spec:
  type: image
  params:
    - name: url
      value: docker-registry.default.svc:5000/mlperf/image-classification:latest
---
