apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: run-run
  namespace: mlperf
spec:
  taskRef:
    name: rnn-run
  serviceAccountName: mlperf
  timeout: "0"
  inputs:
    resources:
      - name: image
        resourceRef:
          name: rnn-build-image 
  podTemplate:
    volumes:
    - name: rnn-dataset-volume
      persistentVolumeClaim:
        claimName: rnn-dataset-pvc
    - name: rnn-runtime-volume
      emptyDir:
        medium: Memory
