apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: run-run
  namespace: mlperf
spec:
  taskRef:
    name: run-benchmark
  serviceAccount: mlperf
  inputs:
    resources:
      - name: build-image
        resourceRef:
          name: build-image