apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: rnn-run
spec:
  inputs:
    resources:
    - name: image
      type: image
  steps:
    - name: run
      image: $(inputs.resources.image.url)
      workingDir: /mlperf/rnn_translator/pytorch
      timeout: 0
      resources:
        limits:
          memory: "20Gi"
          nvidia.com/gpu: 2
        requests:
          memory: "15Gi"
          nvidia.com/gpu: 2
      volumeMounts:
        - name: rnn-dataset-volume
          mountPath: /output_dir
        - name: rnn-runtime-volume
          mountPath: /results
      securityContext:
        privileged: true
      command: ["./run_and_time.sh"]
