apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: sentiment-analysis-pipeline-run
spec:
  serviceAccount: mlperf
  pipelineRef:
    name: sentiment-analysis
  resources:
  - name: sa-repo
    resourceRef:
      name: sa-repo
  - name: sa-build-image
    resourceRef:
      name: sa-build-image